-- =====================================================================
-- 02_magnolia_normalizado.sql
-- Esquema normalizado (3FN) para la tienda de doña Magnolia
-- + migración automática de datos desde pos_general
--
-- No se toca pos_general ni pos_general_short: quedan como respaldo
-- histórico (requisito: "no perder información").
-- =====================================================================

-- =====================================================================
-- PARTE 1: CREACIÓN DE TABLAS NUEVAS
-- =====================================================================

-- Sedes/sucursales de la tienda
CREATE TABLE sucursal (
    id       SERIAL PRIMARY KEY,
    nombre   VARCHAR(100) NOT NULL UNIQUE
);

-- Clientes: un registro por cliente (antes se repetía en cada venta)
CREATE TABLE cliente (
    documento     VARCHAR(20) PRIMARY KEY,
    nombre        VARCHAR(100) NOT NULL,
    ciudad        VARCHAR(50),
    departamento  VARCHAR(50),
    telefono      VARCHAR(20)
);

-- Vendedores: un registro por vendedor, ligado a su sucursal
CREATE TABLE vendedor (
    documento    VARCHAR(20) PRIMARY KEY,
    nombre       VARCHAR(100) NOT NULL,
    sucursal_id  INTEGER NOT NULL REFERENCES sucursal(id)
);

-- Categorías de producto
CREATE TABLE categoria (
    id      SERIAL PRIMARY KEY,
    nombre  VARCHAR(50) NOT NULL UNIQUE
);

-- Proveedores: ahora se pueden insertar sin necesidad de tener ventas
CREATE TABLE proveedor (
    id            SERIAL PRIMARY KEY,
    nombre        VARCHAR(100) NOT NULL UNIQUE,
    ciudad        VARCHAR(50),
    departamento  VARCHAR(50)
);

-- Productos: cada producto pertenece a una categoría y un proveedor
CREATE TABLE producto (
    codigo         VARCHAR(20) PRIMARY KEY,
    nombre         VARCHAR(100) NOT NULL,
    categoria_id   INTEGER NOT NULL REFERENCES categoria(id),
    subcategoria   VARCHAR(50) DEFAULT 'NA',
    proveedor_id   INTEGER NOT NULL REFERENCES proveedor(id) ON DELETE RESTRICT
);

-- Encabezado de venta: quién compró, quién vendió, cómo pagó
CREATE TABLE venta (
    id_venta            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha               TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    cliente_documento   VARCHAR(20) REFERENCES cliente(documento),
    vendedor_documento  VARCHAR(20) REFERENCES vendedor(documento),
    metodo_pago         mpago NOT NULL DEFAULT 'efectivo',
    banco               VARCHAR(50)
);

-- Detalle de venta: qué productos y cantidades incluyó cada venta
CREATE TABLE detalle_venta (
    venta_id         INTEGER REFERENCES venta(id_venta) ON DELETE CASCADE,
    producto_codigo  VARCHAR(20) REFERENCES producto(codigo) ON DELETE RESTRICT,
    cantidad         INTEGER CHECK (cantidad > 0),
    precio_unitario  NUMERIC(10,2) DEFAULT 0 CHECK (precio_unitario >= 0),
    garantia_meses   INTEGER CHECK (garantia_meses >= 0),
    PRIMARY KEY (venta_id, producto_codigo)
);

-- =====================================================================
-- PARTE 2: MIGRACIÓN DE DATOS DESDE pos_general
-- Orden importante: primero las tablas "padre", luego las que dependen
-- de ellas (por las llaves foráneas).
-- Cuando un cliente/proveedor/producto aparece con datos distintos en
-- varias filas viejas (ej. cambió de ciudad), se toma el valor de su
-- venta más reciente (ORDER BY fecha DESC) como el valor "actual".
-- =====================================================================

-- 1) Sucursales (a partir del texto libre vendedor_sucursal)
INSERT INTO sucursal (nombre)
SELECT DISTINCT vendedor_sucursal
FROM pos_general
WHERE vendedor_sucursal IS NOT NULL;

-- 2) Clientes
INSERT INTO cliente (documento, nombre, ciudad, departamento, telefono)
SELECT DISTINCT ON (cliente_documento)
       cliente_documento, cliente_nombre, cliente_ciudad,
       cliente_departamento, cliente_telefono
FROM pos_general
WHERE cliente_documento IS NOT NULL
ORDER BY cliente_documento, fecha DESC;

-- 3) Vendedores (ligados a su sucursal)
INSERT INTO vendedor (documento, nombre, sucursal_id)
SELECT DISTINCT ON (pg.vendedor_documento)
       pg.vendedor_documento, pg.vendedor_nombre, s.id
FROM pos_general pg
JOIN sucursal s ON s.nombre = pg.vendedor_sucursal
WHERE pg.vendedor_documento IS NOT NULL
ORDER BY pg.vendedor_documento, pg.fecha DESC;

-- 4) Categorías
INSERT INTO categoria (nombre)
SELECT DISTINCT categoria
FROM pos_general
WHERE categoria IS NOT NULL;

-- 5) Proveedores (ahora entidad independiente)
INSERT INTO proveedor (nombre, ciudad, departamento)
SELECT DISTINCT ON (proveedor_nombre)
       proveedor_nombre, proveedor_ciudad, proveedor_departamento
FROM pos_general
WHERE proveedor_nombre IS NOT NULL
ORDER BY proveedor_nombre, fecha DESC;

-- 6) Productos (ligados a categoría y proveedor)
INSERT INTO producto (codigo, nombre, categoria_id, subcategoria, proveedor_id)
SELECT DISTINCT ON (pg.producto_codigo)
       pg.producto_codigo, pg.producto_nombre, c.id, pg.subcategoria, pr.id
FROM pos_general pg
JOIN categoria c  ON c.nombre = pg.categoria
JOIN proveedor pr ON pr.nombre = pg.proveedor_nombre
WHERE pg.producto_codigo IS NOT NULL
ORDER BY pg.producto_codigo, pg.fecha DESC;

-- 7) Ventas (encabezado) — se conservan los mismos id_venta originales
INSERT INTO venta (id_venta, fecha, cliente_documento, vendedor_documento,
                    metodo_pago, banco)
SELECT id_venta, fecha, cliente_documento, vendedor_documento,
       metodo_pago, banco
FROM pos_general;

-- Ajustar la secuencia de id_venta para que los próximos INSERT
-- continúen después del máximo id migrado
SELECT setval(
    pg_get_serial_sequence('venta', 'id_venta'),
    COALESCE((SELECT MAX(id_venta) FROM venta), 1)
);

-- 8) Detalle de venta (producto, cantidad, precio, garantía de cada venta)
INSERT INTO detalle_venta (venta_id, producto_codigo, cantidad,
                            precio_unitario, garantia_meses)
SELECT id_venta, producto_codigo, cantidad, precio_unitario, garantia_meses
FROM pos_general;

-- =====================================================================
-- PARTE 3: VERIFICACIÓN RÁPIDA (opcional, solo para confirmar conteos)
-- =====================================================================
SELECT 'pos_general'    AS tabla, COUNT(*) FROM pos_general
UNION ALL SELECT 'venta',          COUNT(*) FROM venta
UNION ALL SELECT 'detalle_venta',  COUNT(*) FROM detalle_venta
UNION ALL SELECT 'cliente',        COUNT(*) FROM cliente
UNION ALL SELECT 'vendedor',       COUNT(*) FROM vendedor
UNION ALL SELECT 'sucursal',       COUNT(*) FROM sucursal
UNION ALL SELECT 'proveedor',      COUNT(*) FROM proveedor
UNION ALL SELECT 'categoria',      COUNT(*) FROM categoria
UNION ALL SELECT 'producto',       COUNT(*) FROM producto;
